[package]
name = "quizler"
version = "0.0.0"
edition = "2021"
description = "Offline quiz game"
license = "MIT"
authors = ["Jacobtread <jacobtread@gmail.com>"]
repository = "https://github.com/jacobtread/Quizler-v2"
readme = "../README.md"
keywords = ["quizler", "game"]


[dependencies]
actix = "0.13"
actix-web = "4"
actix-web-actors = "4"
actix-rt = "2.8.0"

log = "0.4"
env_logger = "0.10"
dotenvy = "0.15"


serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
rand_core = "0.6.4"

[dependencies.uuid]
version = "1.3.2"
features = ["v4", "fast-rng", "macro-diagnostics", "serde"]
