name: Build
on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
env:
    CARGO_TERM_COLOR: always
jobs:
    build-frontend:
        name: Build Frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Frontend
              uses: actions/checkout@v7

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: setup pnpm and install dependencies
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
              with:
                  run_install: |
                      - cwd: frontend
                        args: [--frozen-lockfile]

            - name: Build frontend
              working-directory: frontend
              run: pnpm run build

            - name: Upload frontend artifact
              uses: actions/upload-artifact@v7
              with:
                  name: frontend-build
                  path: frontend/dist/

    build:
        name: Build Backend
        needs: [build-frontend]
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest, windows-latest]
                include:
                    - os: ubuntu-latest
                      file: quizler
                      file_name: Ubuntu Build
                    - os: windows-latest
                      file: quizler.exe
                      file_name: Windows Build
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v7

            - name: Download frontend artifact
              uses: actions/download-artifact@v8
              with:
                  name: frontend-build
                  merge-multiple: true
                  path: backend/public/

            - name: Set up Rust
              uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
              with:
                  toolchain: stable

            - name: Build Backend
              working-directory: ./backend
              run: cargo build --verbose

            - name: Run tests
              working-directory: ./backend
              run: cargo test --verbose

            - name: Upload artifact
              uses: actions/upload-artifact@v7
              with:
                  name: ${{ matrix.file_name }}
                  path: "./backend/target/debug/${{ matrix.file }}"
