name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Frontend
        working-directory: ./frontend
        run: yarn && yarn dist
      - name: Build Backend
        working-directory: ./backend
        run: cargo build --verbose
      - name: Run tests
        working-directory: ./backend
        run: cargo test --verbose
