name: Frontend Build

on:
    workflow_call:

jobs:
    build-frontend:
        name: Build Frontend
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Frontend
              uses: actions/checkout@v7

            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: setup pnpm and install dependencies
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6
              with:
                  run_install: |
                      - args: [--frozen-lockfile]

            - name: Build frontend
              shell: bash
              run: pnpm --filter frontend run build

            - name: Upload frontend artifact
              uses: actions/upload-artifact@v7
              with:
                  name: frontend-build
                  path: frontend/dist/
